### ISSUE TITLE
TK#8 - Crear una página informativa sobre el funcionamiento de las rifas online

### ISSUE THREAD

**Issue by vanemanza** [vanemanza/ISPC_Proyecto_Integrador#30]
Antes de pasar al formulario, el usuario rifador debería ver una página donde se le explique cuales son los pasos a seguir para crear una rifa, luego tendrá la opción de crearla o ver una demo, esto último quedará para una etapa siguiente del proyecto.

**Comment by vanemanza** [comment]
Se la reasigno a Braian, porque lo hizo él.

**Comment by dannacruz20** [comment]
tarea realizada en sprint1
